global:
  resolve_timeout: 5m

route:
  receiver: 'default'
  routes:
  - match:
      severity: 'warning'
    receiver: 'default'
  - match:
      severity: 'critical'
    receiver: 'default'

  

receivers:
- name: 'default'
  email_configs:
  - to: 'kuroonmyouji@gmail.com'
    from: 'kuroonmyouji@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'kuroonmyouji@gmail.com'
    auth_password: 'apnl hegw fmqm oshk'