services:
  ubuntu:
    build: ./test1
    volumes: 
      - ./test1/prometheus.yml:/app/prometheus.yml

  prometheus:
    image: prom/prometheus
    volumes:
      - ./test1/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    ports:
      - "9090:9090"
    #network_mode: "host"
    depends_on: 
      - ubuntu

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./data:/var/lib/grafana
    ports:
      - "3000:3000"
    #network_mode: "host"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    #network_mode: "host"
    
