global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: 
          - '192.168.33.10:9100'
          - '192.168.33.11:9100'

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: 
            - 'localhost:9093'
