global:
  scrape_interval: 3s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - '192.168.1.2:9090'
  - job_name: node_exporter
    static_configs:
      - targets:
rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '192.168.1.4:9093'