global:
  scrape_interval: 3s

scrape_configs:
  - job_name: node_exporter
    static_configs:
      - targets:
rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '172.17.0.2:9093'