FROM ubuntu

COPY run.sh /app/run.sh
COPY iventory.yml /app/iventory.yml
COPY prometheus.yml /app/prometheus.yml

RUN chmod +x /app/run.sh
RUN echo "hello" > /app/hello.yml
ENTRYPOINT ["/app/run.sh"]
