Vagrant.configure("2") do |config|
    config.vm.box = "centos/8"
    
    config.vm.define "web" do |web|
      web.vm.hostname = "web"
      web.vm.network "private_network", ip: "192.168.33.10"
    end
    
    config.vm.define "db" do |db|
      db.vm.hostname = "db"
      db.vm.network "private_network", ip: "192.168.33.11"
    end

    config.vm.define "test1" do |test1|
      test1.vm.hostname = "test1"
      test1.vm.network "private_network", ip: "192.168.33.21"
    end

    config.vm.define "test2" do |test2|
      test2.vm.hostname = "test2"
      test2.vm.network "private_network", ip: "192.168.33.22"
    end

    config.vm.network "forwarded_port", guest: 80, host: 4321, auto_correct: true
    config.vm.usable_port_range = (8000..9000)
  end