Vagrant.configure("2") do |config|
    config.vm.box = "centos/8"
    
    config.vm.define "web" do |web|
      web.vm.hostname = "web"
      web.vm.network "private_network", ip: "192.168.33.10"
    end
    
    config.vm.define "db" do |db|
      db.vm.hostname = "db"
      db.vm.network "private_network", ip: "192.168.33.11"
    end
    config.vm.network "forwarded_port", guest: 80, host: 1234, auto_correct: true
    config.vm.usable_port_range = (8000..9000)
  end